apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: lachisenarath576259/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_Key
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: webapps
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
