apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx # Match the labels used in the Pod template
  template:
    metadata:
      labels:
        app: nginx # Labels for the Pod template
    spec:
      containers:
        - name: nginx
          image: lachisenarath576259/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_Key
