apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lachisenarath576259/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_Key
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: webapps
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 80
      targetPort: 80

  apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: webapps
spec:
  selector:
    app: default-http-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Adjust targetPort if your backend is running on a different port

