apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: lachisenarath576259/client

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: webapps
spec:
  selector:
    app: client
    type: LoadBalancer
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
