apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: webapps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true" # This enables regex matching
    nginx.ingress.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/do-loadbalancer-hostname: "tickets.chathukaviduranga.com"
spec:
  ingressClassName: nginx
  rules:
    - host: tickets.chathukaviduranga.com
      http:
        paths:
          - pathType: Prefix
            path: /api/users/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
